content:
    name: Content
    roles: false
    route: page_list
    links:
        medias:
            roles: false
            name: Medias
            route: media_list
        pages:
            roles: false
            name: Pages
            route: page_list

design:
    name: Design
    roles: [ROLE_USER]
    route: layout_list
    links:
        layouts:
            roles: false
            name: Layouts
            route: layout_list
        snippets:
            roles: false
            name: Snippets
            route: snippet_list

settings:
    name: Settings
    roles: false
    route: user_preferences
    links:
        personal:
            roles: false
            name: Personal
            route: user_preferences
        users:
            roles: [ROLE_ADMIN]
            name: Users
            route: user_list
