# Admin routing
login:
    pattern:  /admin
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:login }

login_check:
    pattern:   /admin/login

logout:
    pattern:   /admin/logout

user_accessDenied:
    pattern: /admin/access-denied
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:accessDenied }

# User routing
user_list:
    pattern:  /admin/users
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:list, tab: settings, nav: users }

user_edit:
    pattern:  /admin/users/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, self: false, tab: settings, nav: users }

user_new:
    pattern:  /admin/users/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: false, tab: settings, nav: users }

user_remove:
    pattern:  /admin/users/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:remove, tab: settings, nav: users }

user_preferences:
    pattern:  /admin/preferences/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: true, tab: settings, nav: personal }

user_preferencesUpdate:
    pattern:  /admin/preferences/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, id: null, self: true, tab: settings, nav: personal }

user_update:
    pattern:  /admin/users/{id}/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:edit, self: false, tab: settings, nav: personal }

user_checkSessionLocale:
    pattern:  /admin/check-session/{redirect_route}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\User:checkSessionLocale }

# Page routing
page_list:
    pattern:  /admin/pages
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:index, tab: content, nav: pages }

page_new:
    pattern:  /admin/pages/{parent_id}/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, id: null, tab: content, nav: pages }

page_edit:
    pattern:  /admin/pages/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, tab: content, nav: pages }

page_update:
    pattern:  /admin/pages/{id}/update
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:edit, tab: content, nav: pages }

page_remove:
    pattern:  /admin/pages/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:remove, tab: content, nav: pages }

page_expand:
    pattern:  /admin/pages/{id}/expand/{level}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Page:expand, tab: content, nav: pages }

# Layout routing
layout_new:
    pattern: /admin/layouts/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, id: null, tab: design, nav: layouts }

layout_update:
    pattern: /admin/layouts/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, tab: design, nav: layouts }

layout_edit:
    pattern: /admin/layouts/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:edit, tab: design, nav: layouts }

layout_list:
    pattern: /admin/layouts
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:index, tab: design, nav: layouts }

layout_remove:
    pattern: /admin/layouts/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Layout:remove, tab: design, nav: layouts }

# Snippet routing
snippet_new:
    pattern: /admin/snippets/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, id: null, tab: design, nav: snippets }

snippet_update:
    pattern: /admin/snippets/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, tab: design, nav: snippets }

snippet_edit:
    pattern: /admin/snippets/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:edit, tab: design, nav: snippets }

snippet_list:
    pattern: /admin/snippets
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:index, tab: design, nav: snippets }

snippet_remove:
    pattern: /admin/snippets/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Snippet:remove, tab: design, nav: snippets }

# Media routing
media_new:
    pattern: /admin/medias/new
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, id: null, tab: content, nav: medias }

media_update:
    pattern: /admin/medias/{id}
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, tab: content, nav: medias }

media_edit:
    pattern: /admin/medias/{id}/edit
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:edit, tab: content, nav: medias }

media_list:
    pattern: /admin/medias
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:index, tab: content, nav: medias }

media_remove:
    pattern: /admin/medias/{id}/remove
    defaults: { _controller: TheodoRogerCmsBundle:Backend\Media:remove, tab: content, nav: medias }

# ESI routing
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

# Frontend routing
page:
    pattern: /{slug}
    defaults: { _controller: TheodoRogerCmsBundle:Frontend\Frontend:page, slug: 'homepage'}
    requirements:
        slug: ".+"