parameters:
    thoth.twig.loader.class: Theodo\ThothCmsBundle\Extensions\Twig\TwigLoaderRepository
    thoth.caching.class: Theodo\ThothCmsBundle\Extensions\Twig\TwigCacheDatabase
    thoth.content_repository.class: Theodo\ThothCmsBundle\Repository\ContentEntityRepository
    thoth.routing.class: Theodo\ThothCmsBundle\Extensions\Twig\Extension\ThothRoutingExtension
    thoth.twig.extension.actions.class: Theodo\ThothCmsBundle\Extensions\Twig\Extension\ThothActionsExtension
    validator.twig_syntax.class: Theodo\ThothCmsBundle\Validator\TwigSyntaxValidator

    # Timestampable listener class
    gedmo.timestampable.listener.class: Gedmo\Timestampable\TimestampableListener

services:
    thoth.content_repository:
        class: %thoth.content_repository.class%
        arguments: ['@doctrine.orm.entity_manager']
    thoth.twig.loader:
        class: %thoth.twig.loader.class%
        arguments: ['@thoth.content_repository', '@twig.loader', %thoth.twig.loader.fallback_path%]
    thoth.twig:
        class: %twig.class%
        arguments: ['@thoth.twig.loader', %twig.options%]
    thoth.templating:
        class: %templating.engine.twig.class%
        arguments: ['@thoth.twig', '@templating.name_parser', '@templating.globals']
    thoth.caching:
        class: %thoth.caching.class%
        arguments: ['@thoth.twig']
    thoth.routing:
        class: %thoth.routing.class%
        arguments: ['@router', '@doctrine.orm.entity_manager']
        tags:
            - { name: thoth.twig.extension }
            - { name: twig.extension }
    thoth.twig.extension.actions:
        class: %thoth.twig.extension.actions.class%
        arguments: ['@service_container']
        tags:
            - { name: thoth.twig.extension }
    validator.twig_syntax:
        class: %validator.twig_syntax.class%
        arguments: ['@thoth.twig']
        tags:
            - { name: validator.constraint_validator, alias: validator.twig_syntax }

    # Timestampable listener
    gedmo.timestampable.listener:
        class: %gedmo.timestampable.listener.class%
        tags:
            - { name: doctrine.event_listener, event: onFlush }
