parameters:
    roger.twig.loader.fallback_path: ~ # defines the path of your templates if you want to mix DB-stored templates and file templates
    roger.twig.loader.class: Theodo\RogerCmsBundle\Extensions\Twig\TwigLoaderRepository
    roger.twig.extension.actions.class: Theodo\RogerCmsBundle\Extensions\Twig\Extension\RogerActionsExtension

    roger.entity_manager.name: default

    roger.user_provider.class: Symfony\Bridge\Doctrine\Security\User\EntityUserProvider
    roger.user_provider.user.class: Theodo\RogerCmsBundle\Entity\User
    roger.user_provider.user.parameter: username

    roger.caching.class: Theodo\RogerCmsBundle\Extensions\Twig\TwigCacheDatabase

    roger.content_repository.class: Theodo\RogerCmsBundle\Repository\ContentEntityRepository

    roger.routing.class: Theodo\RogerCmsBundle\Extensions\Twig\Extension\RogerRoutingExtension

    validator.twig_syntax.class: Theodo\RogerCmsBundle\Validator\TwigSyntaxValidator

    roger.admin.layout:           'TheodoRogerCmsBundle::base_layout.html.twig'
    roger.admin.page.index:       'TheodoRogerCmsBundle::Page/base_index.html.twig'
    roger.admin.page.edit:        'TheodoRogerCmsBundle::Page/base_edit.html.twig'
    roger.admin.page.remove:      'TheodoRogerCmsBundle::Page/base_remove.html.twig'
    roger.admin.page.expand:      'TheodoRogerCmsBundle::Page/page-list.html.twig'
    roger.admin.page.site_map:    'TheodoRogerCmsBundle::Page/page-list.html.twig'
    roger.admin.layout.index:     'TheodoRogerCmsBundle::Layout/base_index.html.twig'
    roger.admin.layout.edit:      'TheodoRogerCmsBundle::Layout/base_edit.html.twig'
    roger.admin.layout.remove:    'TheodoRogerCmsBundle::Layout/base_remove.html.twig'
    roger.admin.media.index:      'TheodoRogerCmsBundle::Media/base_index.html.twig'
    roger.admin.media.edit:       'TheodoRogerCmsBundle::Media/base_edit.html.twig'
    roger.admin.media.remove:     'TheodoRogerCmsBundle::Media/base_remove.html.twig'
    roger.admin.snippet.index:    'TheodoRogerCmsBundle::Snippet/base_index.html.twig'
    roger.admin.snippet.edit:     'TheodoRogerCmsBundle::Snippet/base_edit.html.twig'
    roger.admin.snippet.remove:   'TheodoRogerCmsBundle::Snippet/base_remove.html.twig'
    roger.admin.user.index:       'TheodoRogerCmsBundle::User/base_index.html.twig'
    roger.admin.user.edit:        'TheodoRogerCmsBundle::User/base_edit.html.twig'
    roger.admin.user.remove:      'TheodoRogerCmsBundle::User/base_remove.html.twig'
    roger.admin.user.preferences: 'TheodoRogerCmsBundle::User/base_preferences.html.twig'
    roger.admin.languages:
        - fr_FR
        - en_GB
        - de_DE
        - fr_BE
        - nl_BE
        - nl_NL
        - it_IT


    # Timestampable listener class
    gedmo.timestampable.listener.class: Gedmo\Timestampable\TimestampableListener

services:
    roger.user_provider:
        class: %roger.user_provider.class%
        arguments:
            - '@doctrine.orm.entity_manager'
            - %roger.user_provider.user.class%
            - %roger.user_provider.user.parameter%

    roger.content_repository:
        class: %roger.content_repository.class%
        arguments: ['@doctrine.orm.entity_manager']

    roger.twig.loader:
        class: %roger.twig.loader.class%
        arguments: ['@roger.content_repository', '@twig.loader', %roger.twig.loader.fallback_path%, '@kernel']
        calls:
            - [setSession, ['@session']]

    roger.twig:
        class: %twig.class%
        arguments: ['@roger.twig.loader', %twig.options%]

    roger.templating:
        class: %templating.engine.twig.class%
        arguments: ['@roger.twig', '@templating.name_parser', '@templating.globals']

    roger.caching:
        class: %roger.caching.class%
        arguments: ['@roger.twig']

    roger.routing:
        class: %roger.routing.class%
        arguments: ['@router', '@doctrine.orm.entity_manager']
        tags:
            - { name: roger.twig.extension }
            - { name: twig.extension }

    roger.twig.extension.actions:
        class: %roger.twig.extension.actions.class%
        arguments: ['@service_container']
        tags:
            - { name: roger.twig.extension }
            - { name: twig.extension }

    validator.twig_syntax:
        class: %validator.twig_syntax.class%
        arguments: ['@roger.twig']
        tags:
            - { name: validator.constraint_validator, alias: validator.twig_syntax }

    doctrine.orm.validator.unique:
        class: Theodo\RogerCmsBundle\Validator\Constraints\RogerUniqueEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: doctrine.orm.validator.unique }
        arguments: ['@doctrine']
