# Admin routing
login:
    pattern:  /cms
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:login }

login_check:
    pattern:  /cms/login

logout:
    pattern:   /cms/logout
    
user_accessDenied:
    pattern: /cms/access-denied
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:accessDenied }

# User routing
user_list:
    pattern:  /cms/users
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:list }

user_edit:
    pattern:  /cms/users/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:edit, self: false }

user_new:
    pattern:  /cms/users/new
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:edit, id: null, self: false }

user_remove:
    pattern:  /cms/users/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:remove }

user_preferences:
    pattern:  /cms/preferences/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:edit, id: null, self: true }

user_preferencesUpdate:
    pattern:  /cms/preferences/update
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:edit, id: null, self: true }

user_update:
    pattern:  /cms/users/{id}/update
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:edit, self: false }

user_checkSessionLocale:
    pattern:  /cms/check-session/{redirect_route}
    defaults: { _controller: TheodoThothCmsBundle:Backend\User:checkSessionLocale }

# Page routing
page_list:
    pattern:  /cms/pages
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:index }

page_new:
    pattern:  /cms/pages/{parent_id}/new
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:edit, id: null }

page_edit:
    pattern:  /cms/pages/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:edit }

page_update:
    pattern:  /cms/pages/{id}/update
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:edit }

page_remove:
    pattern:  /cms/pages/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:remove }

page_expand:
    pattern:  /cms/pages/{id}/expand/{level}
    defaults: { _controller: TheodoThothCmsBundle:Backend\Page:expand }

# Layout routing
layout_new:
    pattern: /cms/layouts/new
    defaults: { _controller: TheodoThothCmsBundle:Backend\Layout:edit, id: null }

layout_update:
    pattern: /cms/layouts/{id}
    defaults: { _controller: TheodoThothCmsBundle:Backend\Layout:edit }

layout_edit:
    pattern: /cms/layouts/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\Layout:edit }

layout_list:
    pattern: /cms/layouts
    defaults: { _controller: TheodoThothCmsBundle:Backend\Layout:index }

layout_remove:
    pattern: /cms/layouts/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Backend\Layout:remove }

# Snippet routing
snippet_new:
    pattern: /cms/snippets/new
    defaults: { _controller: TheodoThothCmsBundle:Backend\Snippet:edit, id: null }

snippet_update:
    pattern: /cms/snippets/{id}
    defaults: { _controller: TheodoThothCmsBundle:Backend\Snippet:edit }

snippet_edit:
    pattern: /cms/snippets/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\Snippet:edit }

snippet_list:
    pattern: /cms/snippets
    defaults: { _controller: TheodoThothCmsBundle:Backend\Snippet:index }

snippet_remove:
    pattern: /cms/snippets/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Backend\Snippet:remove }

# Media routing
media_new:
    pattern: /cms/medias/new
    defaults: { _controller: TheodoThothCmsBundle:Backend\Media:edit, id: null }

media_update:
    pattern: /cms/medias/{id}
    defaults: { _controller: TheodoThothCmsBundle:Backend\Media:edit }

media_edit:
    pattern: /cms/medias/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Backend\Media:edit }

media_list:
    pattern: /cms/medias
    defaults: { _controller: TheodoThothCmsBundle:Backend\Media:index }

media_remove:
    pattern: /cms/medias/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Backend\Media:remove }

# ESI routing
_internal:
    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
    prefix:   /_internal

# Frontend routing
page:
    pattern: /{slug}
    defaults: { _controller: TheodoThothCmsBundle:Frontend\Frontend:page, slug: 'homepage'}
    requirements:
        slug: ".+"
