parameters:
    thoth.twig.loader.class: Theodo\ThothCmsBundle\Extensions\Twig_Loader_Repository
    thoth.caching.class: Theodo\ThothCmsBundle\Extensions\Twig_Cache_Database
    thoth.content_repository.class: Theodo\ThothCmsBundle\Repository\ContentEntityRepository
    validator.twig_syntax.class: Theodo\ThothCmsBundle\Validator\TwigSyntaxValidator

services:
    thoth.content_repository:
        class: %thoth.content_repository.class%
        arguments: ['@doctrine.orm.entity_manager']
    thoth.twig.loader:
        class: %thoth.twig.loader.class%
        arguments: ['@thoth.content_repository']
    thoth.twig:
        class: %twig.class%
        arguments: ['@thoth.twig.loader', %twig.options%]
    thoth.templating:
        class: %templating.engine.twig.class%
        arguments: ['@thoth.twig', '@templating.name_parser', '@templating.globals']
    thoth.caching:
        class: %thoth.caching.class%
        arguments: ['@thoth.twig']
    validator.twig_syntax:
        class: %validator.twig_syntax.class%
        arguments: ['@thoth.twig']
        tags:
            - { name: validator.constraint_validator, alias: validator.twig_syntax }
