parameters:
    thoth_frontend.twig.loader.class: Theodo\ThothCmsBundle\Extensions\Twig_Loader_Database
    thoth_frontend.caching.class: Theodo\ThothCmsBundle\Extensions\Twig_Cache_Database

services:
    thoth_frontend.twig.loader:
        class: %thoth_frontend.twig.loader.class%
        arguments: ['@doctrine.orm.entity_manager']
    thoth_frontend.twig:
        class: %twig.class%
        arguments: ['@thoth_frontend.twig.loader', %twig.options%]
    thoth_frontend.templating:
        class: %templating.engine.twig.class%
        arguments: ['@thoth_frontend.twig', '@templating.name_parser', '@templating.globals']
    thoth_frontend.caching:
        class: %thoth_frontend.caching.class%
        arguments: ['@thoth_frontend.twig']