imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true
    translator: { fallback: en }
    esi: { enabled: true }

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8
            test:
                driver:   %database_driver%
                host:     %database_host%
                dbname:   %test_database_name%
                user:     %database_user%
                password: %database_password%
                charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%

        default_entity_manager: default
        entity_managers:
            default:
                connection:   default
                mappings:
                    TheodoThothCmsBundle: ~
                    StofDoctrineExtensionsBundle: false # The mapping is only needed when using the Translatable or the Loggable behaviors
            test:
                connection:   test
                mappings:
                    TheodoThothCmsBundle: ~
                    StofDoctrineExtensionsBundle: false # The mapping is only needed when using the Translatable or the Loggable behaviors

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false

# Load thoth cms service
theodo_thoth_cms: ~

stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            timestampable: true
            tree:          false
            sluggable:     false
            translatable:  false
            loggable:      false
        test:
            timestampable: true
            tree:          false
            sluggable:     false
            translatable:  false
            loggable:      false
