homepage:
    pattern:  /
    defaults: { _controller: SadiantCmsBundle:Page:index }

layout_new:
    pattern: /admin/layout/new
    defaults: { _controller: SadiantCmsBundle:Layout:new }

layout_update:
    pattern: /admin/layout/{id}
    defaults: { _controller: SadiantCmsBundle:Layout:update }

layout_edit:
    pattern: /admin/layout/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Layout:edit }

layout_list:
    pattern: /admin/layout
    defaults: { _controller: SadiantCmsBundle:Layout:index }

snippet_new:
    pattern: /admin/snippet/new
    defaults: { _controller: SadiantCmsBundle:Snippet:new }

snippet_update:
    pattern: /admin/snippet/{id}
    defaults: { _controller: SadiantCmsBundle:Snippet:update }

snippet_edit:
    pattern: /admin/snippet/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Snippet:edit }

snippet_list:
    pattern: /admin/snippet
    defaults: { _controller: SadiantCmsBundle:Snippet:index }

default:
    pattern: /visible/{slug}
    defaults: { _controller: SadiantCmsBundle:Page:visible }
