homepage:
    pattern:  /
    defaults: { _controller: SadiantCmsBundle:Page:index }

layout_new:
    pattern: /layout/new
    defaults: { _controller: SadiantCmsBundle:Layout:new }

layout_update:
    pattern: /layout/{id}
    defaults: { _controller: SadiantCmsBundle:Layout:update }

layout_edit:
    pattern: /layout/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Layout:edit }

layout_list:
    pattern: /layout
    defaults: { _controller: SadiantCmsBundle:Layout:index }

snippet_new:
    pattern: /snippet/new
    defaults: { _controller: SadiantCmsBundle:Snippet:new }

snippet_update:
    pattern: /snippet/{id}
    defaults: { _controller: SadiantCmsBundle:Snippet:update }

snippet_edit:
    pattern: /snippet/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Snippet:edit }

snippet_list:
    pattern: /snippet
    defaults: { _controller: SadiantCmsBundle:Snippet:index }
