# Admin routing
login:
    pattern:  /cms
    defaults: { _controller: TheodoThothCmsBundle:User:login }

login_check:
    pattern:  /cms/login

logout:
    pattern:   /cms/logout
    
user_accessDenied:
    pattern: /cms/access-denied
    defaults: { _controller: TheodoThothCmsBundle:User:accessDenied }

# User routing
user_list:
    pattern:  /cms/users
    defaults: { _controller: TheodoThothCmsBundle:User:list }

user_edit:
    pattern:  /cms/users/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:User:edit }

user_new:
    pattern:  /cms/users/new
    defaults: { _controller: TheodoThothCmsBundle:User:new }

user_remove:
    pattern:  /cms/users/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:User:remove }

user_preferences:
    pattern:  /cms/preferences/edit
    defaults: { _controller: TheodoThothCmsBundle:User:preferences }

user_preferencesUpdate:
    pattern:  /cms/preferences/update
    defaults: { _controller: TheodoThothCmsBundle:User:preferencesUpdate }

user_update:
    pattern:  /cms/users/{id}/update
    defaults: { _controller: TheodoThothCmsBundle:User:update }

user_checkSessionLocale:
    pattern:  /cms/check-session/{redirect_route}
    defaults: { _controller: TheodoThothCmsBundle:User:checkSessionLocale }

# Page routing
page_list:
    pattern:  /cms/pages
    defaults: { _controller: TheodoThothCmsBundle:Page:index }

page_new:
    pattern:  /cms/pages/{id}/new
    defaults: { _controller: TheodoThothCmsBundle:Page:new }

page_edit:
    pattern:  /cms/pages/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Page:edit }

page_update:
    pattern:  /cms/pages/{id}/update
    defaults: { _controller: TheodoThothCmsBundle:Page:update }

page_remove:
    pattern:  /cms/pages/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Page:remove }

page_expand:
    pattern:  /cms/pages/{id}/expand/{level}
    defaults: { _controller: TheodoThothCmsBundle:Page:expand }

# Layout routing
layout_new:
    pattern: /cms/layouts/new
    defaults: { _controller: TheodoThothCmsBundle:Layout:new }

layout_update:
    pattern: /cms/layouts/{id}
    defaults: { _controller: TheodoThothCmsBundle:Layout:update }

layout_edit:
    pattern: /cms/layouts/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Layout:edit }

layout_list:
    pattern: /cms/layouts
    defaults: { _controller: TheodoThothCmsBundle:Layout:index }

layout_remove:
    pattern: /cms/layouts/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Layout:remove }

# Snippet routing
snippet_new:
    pattern: /cms/snippets/new
    defaults: { _controller: TheodoThothCmsBundle:Snippet:new }

snippet_update:
    pattern: /cms/snippets/{id}
    defaults: { _controller: TheodoThothCmsBundle:Snippet:update }

snippet_edit:
    pattern: /cms/snippets/{id}/edit
    defaults: { _controller: TheodoThothCmsBundle:Snippet:edit }

snippet_list:
    pattern: /cms/snippets
    defaults: { _controller: TheodoThothCmsBundle:Snippet:index }

snippet_remove:
    pattern: /cms/snippets/{id}/remove
    defaults: { _controller: TheodoThothCmsBundle:Snippet:remove }

# Frontend routing
page:
    pattern: /{slug}
    defaults: { _controller: TheodoThothCmsBundle:Frontend:page, slug: 'homepage'}
    requirements:
        slug: ".+"
