# Page routing
admin:
    pattern:  /admin
    defaults: { _controller: SadiantCmsBundle:Page:index }

page_list:
    pattern:  /admin/pages
    defaults: { _controller: SadiantCmsBundle:Page:index }

page_new:
    pattern:  /admin/pages/{id}/new
    defaults: { _controller: SadiantCmsBundle:Page:new }

page_edit:
    pattern:  /admin/pages/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Page:edit }

page_update:
    pattern:  /admin/pages/{id}/update
    defaults: { _controller: SadiantCmsBundle:Page:update }

page_remove:
    pattern:  /admin/pages/{id}/remove
    defaults: { _controller: SadiantCmsBundle:Page:remove }

page_expand:
    pattern:  /admin/pages/{id}/expand
    defaults: { _controller: SadiantCmsBundle:Page:expand }

layout_new:
    pattern: /admin/layout/new
    defaults: { _controller: SadiantCmsBundle:Layout:new }

layout_update:
    pattern: /admin/layout/{id}
    defaults: { _controller: SadiantCmsBundle:Layout:update }

layout_edit:
    pattern: /admin/layout/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Layout:edit }

layout_list:
    pattern: /admin/layout
    defaults: { _controller: SadiantCmsBundle:Layout:index }

layout_delete:
    pattern: /admin/layout/{id}/delete
    defaults: { _controller: SadiantCmsBundle:Layout:delete }

snippet_new:
    pattern: /admin/snippet/new
    defaults: { _controller: SadiantCmsBundle:Snippet:new }

snippet_update:
    pattern: /admin/snippet/{id}
    defaults: { _controller: SadiantCmsBundle:Snippet:update }

snippet_edit:
    pattern: /admin/snippet/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Snippet:edit }

snippet_list:
    pattern: /admin/snippet
    defaults: { _controller: SadiantCmsBundle:Snippet:index }

snippet_delete:
    pattern: /admin/snippet/{id}/delete
    defaults: { _controller: SadiantCmsBundle:Snippet:delete }

visible:
    pattern: /visible/{slug}
    defaults: { _controller: SadiantCmsBundle:Page:visible }

