# Admin routing
login:
    pattern:  /admin
    defaults: { _controller: SadiantCmsBundle:User:login }

login_check:
    pattern:  /admin/login

logout:
    pattern:   /admin/logout

# User routing
user_list:
    pattern:  /admin/users
    defaults: { _controller: SadiantCmsBundle:User:list }

user_edit:
    pattern:  /admin/users/{id}/edit
    defaults: { _controller: SadiantCmsBundle:User:edit }

user_new:
    pattern:  /admin/users/new
    defaults: { _controller: SadiantCmsBundle:User:new }

user_remove:
    pattern:  /admin/users/{id}/remove
    defaults: { _controller: SadiantCmsBundle:User:remove }

user_preferences:
    pattern:  /admin/preferences/edit
    defaults: { _controller: SadiantCmsBundle:User:preferences }

user_preferencesUpdate:
    pattern:  /admin/preferences/update
    defaults: { _controller: SadiantCmsBundle:User:preferencesUpdate }

user_update:
    pattern:  /admin/users/{id}/update
    defaults: { _controller: SadiantCmsBundle:User:update }

# Page routing
page_list:
    pattern:  /admin/pages
    defaults: { _controller: SadiantCmsBundle:Page:index }

page_new:
    pattern:  /admin/pages/{id}/new
    defaults: { _controller: SadiantCmsBundle:Page:new }

page_edit:
    pattern:  /admin/pages/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Page:edit }

page_update:
    pattern:  /admin/pages/{id}/update
    defaults: { _controller: SadiantCmsBundle:Page:update }

page_remove:
    pattern:  /admin/pages/{id}/remove
    defaults: { _controller: SadiantCmsBundle:Page:remove }

page_expand:
    pattern:  /admin/pages/{id}/expand/{level}
    defaults: { _controller: SadiantCmsBundle:Page:expand }

# Layout routing
layout_new:
    pattern: /admin/layouts/new
    defaults: { _controller: SadiantCmsBundle:Layout:new }

layout_update:
    pattern: /admin/layouts/{id}
    defaults: { _controller: SadiantCmsBundle:Layout:update }

layout_edit:
    pattern: /admin/layouts/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Layout:edit }

layout_list:
    pattern: /admin/layouts
    defaults: { _controller: SadiantCmsBundle:Layout:index }

layout_remove:
    pattern: /admin/layouts/{id}/remove
    defaults: { _controller: SadiantCmsBundle:Layout:remove }

# Snippet routing
snippet_new:
    pattern: /admin/snippets/new
    defaults: { _controller: SadiantCmsBundle:Snippet:new }

snippet_update:
    pattern: /admin/snippets/{id}
    defaults: { _controller: SadiantCmsBundle:Snippet:update }

snippet_edit:
    pattern: /admin/snippets/{id}/edit
    defaults: { _controller: SadiantCmsBundle:Snippet:edit }

snippet_list:
    pattern: /admin/snippets
    defaults: { _controller: SadiantCmsBundle:Snippet:index }

snippet_remove:
    pattern: /admin/snippets/{id}/remove
    defaults: { _controller: SadiantCmsBundle:Snippet:remove }

# Frontend routing
page:
    pattern: /{slug}
    defaults: { _controller: SadiantCmsBundle:Frontend:page, slug: null }
