security:
    encoders:
        Sadiant\CmsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Sadiant\CmsBundle\Entity\User, property: username }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/admin$
            security: false

        main:
            pattern:    ^/admin/*
            form_login:
                check_path: /admin/login
                login_path: /admin
            logout:
                path:   /admin/logout
                target: /admin
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin/*, roles: ROLE_USER }
        - { path: ^/admin/users, roles: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

