security:
    encoders:
        Theodo\ThothCmsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Theodo\ThothCmsBundle\Entity\User, property: username }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/admin$
            security: false

        main:
            pattern:    ^/admin/*
            form_login:
                check_path:  /admin/login
                login_path:  /admin
                remember_me: true
            logout:
                path:               /admin/logout
                target:             /admin
                invalidate_session: true
            http_basic: true
            remember_me:
                key:      463a06ee69fbea064218b1d02c416125
                lifetime: 86400
                path:     /

    access_control:
        - { path: ^/admin/*, roles: ROLE_USER }
        - { path: ^/admin/users, roles: ROLE_ADMIN }
        - { path: /.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

