security:
    encoders:
        Theodo\ThothCmsBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER:        ROLE_CLIENT
        ROLE_ADMIN:       [ROLE_USER, ROLE_CLIENT]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_CLIENT, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Theodo\ThothCmsBundle\Entity\User, property: username }

    firewalls:
        profiler:
            pattern:  ^/_profiler
            security: false

        wdt:
            pattern:  ^/_wdt
            security: false

        login:
            pattern:  ^/cms$
            security: false

        main:
            pattern:    ^/cms/*
            access_denied_url: /cms/access-denied
            form_login:
                check_path:  /cms/login
                login_path:  /cms
                remember_me: true
            logout:
                path:               /cms/logout
                target:             /cms
                invalidate_session: true
            http_basic: true
            remember_me:
                key:      463a06ee69fbea064218b1d02c416125
                lifetime: 86400
                path:     /

    access_control:
        - { path: ^/cms/users*, roles: ROLE_ADMIN }
        - { path: ^/cms/snippets*, roles: ROLE_USER }
        - { path: ^/cms/layouts*, roles: ROLE_USER }
        - { path: ^/cms/*, roles: ROLE_CLIENT }
        - { path: ^/cms, roles: IS_AUTHENTICATED_ANONYMOUSLY }        
        - { path: ^/.*, role: IS_AUTHENTICATED_ANONYMOUSLY }

