Theodo\ThothCmsBundle\Entity\Role:
    type: entity
    table: role
    repositoryClass: Theodo\ThothCmsBundle\Repository\RoleRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            nullable: false