Theodo\ThothCmsBundle\Entity\Snippet:
    type: entity
    table: snippet
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
            unique: true
        content:
            type: text