Sadiant\CmsBundle\Entity\Snippet:
    type: entity
    table: snippet
    repositoryClass: Sadiant\CmsBundle\Repository\SnippetRepository
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        name:
            type: string
            length: 255
        content:
            type: text